/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import modelo.PessoaVO;
import org.omg.CORBA.UserException;
import servicos.PessoaServicos;
import sun.security.util.Password;

/**
 *
 * @author Fernando Souza & João V.
 * @since 01/06/2014 - 08:50
 * @version 1.9 Beta Magnifico
 */
public class GUICadPessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadPessoa
     */
    public GUICadPessoa() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jlpCadastro = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlNickname = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jlSexo = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlConfSenha = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtNickname = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jtIdade = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jrbMasculino = new javax.swing.JRadioButton();
        jrbFeminino = new javax.swing.JRadioButton();
        jpfSenha = new javax.swing.JPasswordField();
        jpfConfSenha = new javax.swing.JPasswordField();
        jlpCaptcha = new javax.swing.JLayeredPane();
        jlCAPTCHA = new javax.swing.JLabel();
        jcbNSR = new javax.swing.JCheckBox();
        jbCadastrar = new javax.swing.JButton();
        jlMSN = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jlpCadastro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlNome.setText("Nome");

        jlNickname.setText("Nickname");

        jlEmail.setText("Email");

        jlSexo.setText("Sexo");

        jlIdade.setText("Idade");

        jlTelefone.setText("Telefone");

        jlSenha.setText("Senha");

        jlConfSenha.setText("Confirmar Senha");

        bgSexo.add(jrbMasculino);
        jrbMasculino.setText("Masculino");
        jrbMasculino.setActionCommand("Masculino");

        bgSexo.add(jrbFeminino);
        jrbFeminino.setText("Feminino");
        jrbFeminino.setActionCommand("Feminino");

        jlpCaptcha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlCAPTCHA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ddwpok.png"))); // NOI18N

        jcbNSR.setText("Não sou um robô");

        jlpCaptcha.setLayer(jlCAPTCHA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCaptcha.setLayer(jcbNSR, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCaptchaLayout = new javax.swing.GroupLayout(jlpCaptcha);
        jlpCaptcha.setLayout(jlpCaptchaLayout);
        jlpCaptchaLayout.setHorizontalGroup(
            jlpCaptchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCaptchaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbNSR)
                .addGap(31, 31, 31)
                .addComponent(jlCAPTCHA)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpCaptchaLayout.setVerticalGroup(
            jlpCaptchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCaptchaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbNSR)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCaptchaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlCAPTCHA))
        );

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jlpCadastro.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlNickname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlConfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtNickname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtIdade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrbMasculino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jrbFeminino, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jpfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jpfConfSenha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jlpCaptcha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastro.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpCadastroLayout = new javax.swing.GroupLayout(jlpCadastro);
        jlpCadastro.setLayout(jlpCadastroLayout);
        jlpCadastroLayout.setHorizontalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jlConfSenha)
                                .addGap(18, 18, 18)
                                .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(18, 18, 18)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlEmail)
                                .addGap(18, 18, 18)
                                .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlIdade)
                                .addGap(18, 18, 18)
                                .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlSexo)
                                .addGap(18, 18, 18)
                                .addComponent(jrbMasculino)
                                .addGap(41, 41, 41)
                                .addComponent(jrbFeminino))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jlpCadastroLayout.createSequentialGroup()
                                .addComponent(jlNickname)
                                .addGap(18, 18, 18)
                                .addComponent(jtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jlpCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastroLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jbCadastrar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jlpCadastroLayout.setVerticalGroup(
            jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNickname)
                    .addComponent(jtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jrbMasculino)
                    .addComponent(jrbFeminino))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdade)
                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefone)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jlConfSenha)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jlpCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCadastrar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jlMSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMSN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/msn.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlMSN)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMSN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            PessoaVO pVO = new PessoaVO();
            pVO.setNome(jtNome.getText());
            pVO.setNickname(jtNickname.getText());
            pVO.setEmail(jtEmail.getText());
            pVO.setSexo(bgSexo.getSelection().getActionCommand());
            pVO.setTelefone(jtTelefone.getText());
            pVO.setSenha(jpfSenha.getText());
            pVO.setIdade(Integer.parseInt(jtIdade.getText()));
            
            
            PessoaServicos ps = servicos.ServicosFactory.getPessoaServicos();
            ps.cadastrarPessoa(pVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Pessoa cadastrada com sucesso!"+pVO.toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
        
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JCheckBox jcbNSR;
    private javax.swing.JLabel jlCAPTCHA;
    private javax.swing.JLabel jlConfSenha;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlMSN;
    private javax.swing.JLabel jlNickname;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLayeredPane jlpCadastro;
    private javax.swing.JLayeredPane jlpCaptcha;
    private javax.swing.JPasswordField jpfConfSenha;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JRadioButton jrbFeminino;
    private javax.swing.JRadioButton jrbMasculino;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNickname;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
